version: "3.8"
services:
  bot:
    image: "claimant-bot:latest"
    container_name: "claimant-bot"
    volumes:
      - ./.env:/claimant/.env

  clear-db-daemon:
    image: "clear-db-daemon:latest"
    container_name: "clear-db-daemon"
    environment:
      DELAY_SEC: 7200
      DATA_LIFETIME_H: 2
    volumes:
      - ./.env:/clear_db_daemon/.env
    restart: always
    depends_on:
      - bot-db

  #  bot-fsm-storage:
#    image: "redis:alpine"
#    container_name: "bot-fsm-storage"
#    ports:
#      - "6379:6379"
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 5s
#      timeout: 30s
#      retries: 50
#    restart: always
#    command: redis-server --requirepass ${REDIS_PASSWORD}
#    environment:
#      - REDIS_REPLICATION_MODE=master

  bot-db:
    image: "mongo:4.2-bionic"
    container_name: "bot-db"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "127.0.0.1:${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - ./bot-db:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
