version: "3.8"
services:
#  bot:
#    image: "claimant-bot:latest"
#    container_name: "claimant-bot"
#    volumes:
#      - ./.env:/claimant/.env

#  bot-fsm-storage:
#    image: "redis:alpine"
#    container_name: "bot-fsm-storage"
#    ports:
#      - "6379:6379"
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 5s
#      timeout: 30s
#      retries: 50
#    restart: always
#    command: redis-server --requirepass ${REDIS_PASSWORD}
#    environment:
#      - REDIS_REPLICATION_MODE=master

  bot-db:
    image: "mongo:4.2-bionic"
    container_name: "bot-db"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./bot-db:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
