name: Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  python_check:
    name: Check files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          changes_in_bot=$(git diff --name-only HEAD^ HEAD | grep src/bot)
          echo "changes: $changes_in_bot"
          if [[ -z $changes_in_bot ]]; then
              echo "src/bot has no changes. No test run required"
              echo "::set-output name=run_job::false"
          else
              echo "::set-output name=run_job::true"
          fi

  pytest:
    needs: python_check
    if: needs.python_check.outputs.run_job == 'true'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd src/bot
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Test with pytest
      run: |
        cd src/bot
        pytest

